'use strict';
const assert=require('node:assert/strict');const {createHash}=require('node:crypto');const P=require('./renderer');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const player=Object.freeze({portraitSeed:84723911,portraitVersion:1,age:20,height:76,weight:258,jerseyNumber:7});
const school=Object.freeze({primary:'#174d46',secondary:'#ecb45b'});
const digest=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
test('Known seeds produce stable drawing-command goldens',()=>{
 for(const [seed,expected] of [[0,'26b7bdaea3b7867319ed2fafcf9e83f48fc2aee15f2a738155e12679d75b1f81'],[84723911,'f6f7e4c05e7e366e84659dc00295d53875f458f164b2828034a80b2341241b31'],['test-identity','ca1334a060644e65ad0cd782898dddb2034d7b2870b77b2910bf9b5a6dcff8bf']])assert.equal(digest(P.drawingCommands(P.prepare({portraitSeed:seed,age:20,height:76,weight:258}))),expected);
});
test('Repeated and reordered rendering has no effect on identity',()=>{const expected=P.deriveIdentity(84723911);for(let i=0;i<100;i++)P.drawingCommands(P.prepare({portraitSeed:i}));assert.deepEqual(P.deriveIdentity(84723911),expected);});
test('Named random streams do not consume one another',()=>{const a=P.rng(42,'face'),b=P.rng(42,'face');assert.equal(a(),b());const extra=P.rng(42,'extras');for(let i=0;i<99;i++)extra();assert.equal(a(),b());});
test('Save round trip preserves preview identity',()=>assert.deepEqual(P.prepare(player,school),P.prepare(JSON.parse(JSON.stringify(player)),school)));
test('Aging, mass gain and transfer retain identity',()=>{const young=P.prepare({...player,age:17,weight:224},school),older=P.prepare({...player,age:22,weight:270},{primary:'#7d3024'});assert.deepEqual(young.identity,older.identity);assert.ok(older.neck>young.neck);assert.notEqual(young.primary,older.primary);});
test('Every supported appearance edit invalidates its cache key',()=>{const base=P.getCacheKey(player,school);for(const props of [{age:22},{weight:300},{height:80},{jerseyNumber:0},{portraitSeed:1}])assert.notEqual(P.getCacheKey({...player,...props},school),base);for(const options of [{size:128},{pixelRatio:2},{neutral:true},{background:'#123456'},{overrides:{skin:9}},{overrides:{hair:20}},{overrides:{beard:6}},{overrides:{hairColor:2}}])assert.notEqual(P.getCacheKey(player,school,options),base);assert.notEqual(P.getCacheKey(player,{...school,secondary:'#ffffff'}),base);});
test('Accessory cache keys follow effective appearance',()=>{const withExtras={...player,portraitSeed:Array.from({length:100},(_,i)=>i).find(i=>P.deriveIdentity(i).eyeBlack)};assert.notEqual(P.getCacheKey(withExtras,school),P.getCacheKey(withExtras,school,{overrides:{accessories:false}}));});
test('LRU stays bounded and updates recency on hits',()=>{const c=new P.PortraitCache(32),small={width:2,height:2};c.set('a',small);c.set('b',small);c.get('a');c.set('c',small);assert.equal(c.bytes,32);assert.equal(c.get('b'),null);assert.ok(c.get('a'));c.set('large',{width:100,height:100});assert.equal(c.bytes,32);c.clear();assert.equal(c.bytes,0);});
test('Frozen inputs stay unchanged and gameplay randomness is untouched',()=>{const original=Math.random;Math.random=()=>{throw new Error('Gameplay randomness consumed');};try{P.drawingCommands(P.prepare(player,school));}finally{Math.random=original;}assert.equal(player.weight,258);});
test('Invalid fields and seed zero remain finite and repeatable',()=>{const a=P.prepare({portraitSeed:0,height:NaN,weight:Infinity,age:'invalid',jerseyNumber:-99},{primary:'red'});assert.equal(a.identity.seed,'0');assert.equal(a.height,74);assert.equal(a.weight,215);assert.equal(a.number,'0');assert.equal(a.primary,'#174d46');const walk=x=>{if(typeof x==='number')assert.ok(Number.isFinite(x));else if(Array.isArray(x))x.forEach(walk);};walk(P.drawingCommands(a));});
test('Unsupported renderer versions are explicit errors',()=>assert.throws(()=>P.deriveIdentity(1,2),RangeError));
test('100-seed diversity fixture has unique face geometry and broad coverage',()=>{const faces=Array.from({length:100},(_,i)=>P.deriveIdentity(P.hash(`2030:player:${i}`)));assert.equal(new Set(faces.map(f=>JSON.stringify([f.width,f.jaw,f.eyes,f.nose,f.mouth]))).size,100);assert.ok(new Set(faces.map(f=>f.hair)).size>=20);assert.equal(new Set(faces.map(f=>f.skin)).size,10);});
test('All hair / skin combinations draw finite commands',()=>{for(let hair=0;hair<P.HAIR.length;hair++)for(let skin=0;skin<10;skin++){const a=P.prepare(player,school,{overrides:{hair,skin}});const encoded=JSON.stringify(P.drawingCommands(a));assert.ok(!encoded.includes('null'));}});
console.log(`${count} portrait tests passed.`);
