function makeRecruitingBattleSystem(){
 'use strict';
 function focusKey(u){return `${u?.year??0}:${u?.week??0}`}
 function focusRecord(r,teamId){return r?.recruitingFocus?.[String(teamId)]||null}
 function activeFocus(r,t,u){const x=focusRecord(r,t?.id);return !!x&&x.key===focusKey(u)}
 function focusCount(recruits,t,u){return (recruits||[]).filter(r=>activeFocus(r,t,u)).length}
 function toggleFocus(r,t,u,limit=3){
  if(!r||!t||!u)return{ok:false,reason:'No recruit selected.'};if(u.phase!=='regular')return{ok:false,reason:'Recruiting focus is available during the regular season.'};if(r.committed&&r.committed!==t.name)return{ok:false,reason:`${r.name||'This recruit'} is committed elsewhere.`};if(!r.targeted&&r.committed!==t.name)return{ok:false,reason:'Add this recruit to your board first.'};
  r.recruitingFocus??={};const key=String(t.id);if(activeFocus(r,t,u)){delete r.recruitingFocus[key];return{ok:true,active:false,remaining:Math.max(0,limit-focusCount(u.recruits,t,u))}}
  const used=focusCount(u.recruits,t,u);if(used>=limit)return{ok:false,reason:`All ${limit} weekly priority-push slots are already assigned.`};r.recruitingFocus[key]={key:focusKey(u),season:u.year,week:u.week};return{ok:true,active:true,remaining:Math.max(0,limit-used-1)};
 }
 function focusBoost(r,t,u){return activeFocus(r,t,u)?4:0}
 function raceSummary(rows=[],userId=null){
  if(!rows.length)return{rank:null,gap:null,leader:null,label:'No race'};const top=rows[0],userIndex=rows.findIndex(x=>x.t?.id===userId),user=userIndex>=0?rows[userIndex]:null,gap=user?Math.round((user.score-top.score)*10)/10:null;
  let label=userIndex===0?'Leading':userIndex===1&&gap>=-4?'Neck-and-neck':userIndex>=0&&gap>=-9?'Within striking distance':userIndex>=0?'Chasing':'Outside top group';return{rank:userIndex>=0?userIndex+1:null,gap,leader:top.t?.name||null,label};
 }
 function decisionWindow(r,u,summary){const w=u?.week??0,interest=r?.interest??0;if(r?.committed)return r.challenger?'Flip pressure':'Committed';if(w>=9||interest>=88)return'Decision nearing';if(w>=6&&summary?.gap!=null&&summary.gap>=-6)return'Tight race';if(w>=5)return'Board taking shape';return'Open recruitment'}
 function historyRow(r,summary,u){return{season:u.year,week:u.week,interest:Math.round(r.interest||0),trend:Math.round(r.trend||0),rank:summary.rank,gap:summary.gap,leader:summary.leader,committed:r.committed||null,challenger:r.challenger||null,pressure:Number.isFinite(r.pressure)?r.pressure:null}}
 function pushHistory(r,row,limit=16){r.battleHistory??=[];const last=r.battleHistory.at(-1);if(last&&last.season===row.season&&last.week===row.week)r.battleHistory[r.battleHistory.length-1]=row;else r.battleHistory.push(row);if(r.battleHistory.length>limit)r.battleHistory.splice(0,r.battleHistory.length-limit);return r.battleHistory}
 return{focusKey,focusRecord,activeFocus,focusCount,toggleFocus,focusBoost,raceSummary,decisionWindow,historyRow,pushHistory};
}
if(typeof module==='object'&&module.exports){module.exports={makeRecruitingBattleSystem}}
else{
 const recruitingBattleSystem=makeRecruitingBattleSystem(),RECRUITING_FOCUS_LIMIT=3;
 const recruitPitchBeforeV0955Battles=recruitPitch;
 recruitPitch=function(t,r){return recruitPitchBeforeV0955Battles(t,r)+(t?.id===selected()?.id?recruitingBattleSystem.focusBoost(r,t,universe):0)};
 function battleRows(r,n=5){return universe.teams.map(t=>({t,score:recruitPitch(t,r)+(t.name===selected()?.name&&r.targeted?10+r.relationship*.12:0)})).sort((a,b)=>b.score-a.score).slice(0,n)}
 function captureBattleHistory(){const t=selected();if(!t)return;for(const r of universe.recruits||[]){if(!r.targeted&&r.committed!==t.name)continue;const rows=battleRows(r,5),summary=recruitingBattleSystem.raceSummary(rows,t.id);recruitingBattleSystem.pushHistory(r,recruitingBattleSystem.historyRow(r,summary,universe))}}
 const advanceRecruitingBeforeV0955Battles=advanceRecruiting;
 advanceRecruiting=function(){const out=advanceRecruitingBeforeV0955Battles();captureBattleHistory();return out};
 function battleEscape(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function focusButton(r,t){const active=recruitingBattleSystem.activeFocus(r,t,universe);return `<button type="button" class="recruit-focus-btn${active?' active':''}" data-recruit-focus="${battleEscape(r.id)}">${active?'Priority Push Active':'Priority Push'}</button>`}
 function momentumLabel(r){const n=Math.round(r.trend||0);return n>=6?`Heating up +${n}`:n>=2?`Gaining +${n}`:n<=-6?`Sliding ${n}`:n<=-2?`Cooling ${n}`:'Steady'}
 function raceCard(r,t){const rows=battleRows(r,5),s=recruitingBattleSystem.raceSummary(rows,t.id),window=recruitingBattleSystem.decisionWindow(r,universe,s),hist=(r.battleHistory||[]).slice(-4).reverse();return `<div class="recruit-race-card"><div class="recruit-race-head"><div><span class="eyebrow">RECRUITING BATTLE</span><strong>${battleEscape(s.label)}</strong></div><div><span class="pill">${battleEscape(window)}</span> ${focusButton(r,t)}</div></div><div class="recruit-race-kpis"><span><b>${s.rank?`#${s.rank}`:'—'}</b> your position</span><span><b>${s.gap==null?'—':`${s.gap>=0?'+':''}${s.gap}`}</b> gap to leader</span><span><b>${battleEscape(momentumLabel(r))}</b> momentum</span><span><b>${Math.round(r.interest||0)}%</b> interest</span></div><div class="recruit-race-schools">${rows.map((x,i)=>`<div><span>${i+1}. ${battleEscape(x.t.name)}</span><strong>${Math.round(x.score)}</strong></div>`).join('')}</div>${hist.length?`<div class="recruit-race-history">${hist.map(x=>`<span>W${x.week}: ${x.rank?`#${x.rank}`:'—'} · ${x.interest}% · ${x.trend>=0?'+':''}${x.trend}</span>`).join('')}</div>`:''}<small>Priority Push gives this recruit a modest +4 pitch boost for the current week. You may assign ${RECRUITING_FOCUS_LIMIT} per week.</small></div>`}
 function bindRecruitFocus(){const t=selected();$$('[data-recruit-focus]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const r=universe.recruits.find(x=>String(x.id)===String(b.dataset.recruitFocus)),res=recruitingBattleSystem.toggleFocus(r,t,universe,RECRUITING_FOCUS_LIMIT);setStatus(res.ok?(res.active?`${r.name} is a priority push this week. ${res.remaining} focus slot${res.remaining===1?'':'s'} remain.`:`Priority push removed from ${r.name}.`):res.reason);renderRecruiting();renderRecruitBattles()})}
 function renderEnhancedBattleBoard(){const t=selected(),host=$('#recruitBattleBoard');if(!t||!host)return;const open=universe.recruits.filter(r=>r.targeted&&!r.committed),commits=universe.recruits.filter(r=>r.committed===t.name&&(r.challenger||recruitingBattleSystem.activeFocus(r,t,universe))),pool=[...open,...commits].sort((a,b)=>(b.challenger?1:0)-(a.challenger?1:0)||(b.interest||0)-(a.interest||0)).slice(0,8);host.innerHTML=pool.map(r=>{const rows=battleRows(r,3),s=recruitingBattleSystem.raceSummary(rows,t.id),window=recruitingBattleSystem.decisionWindow(r,universe,s);return `<div class="battle-card battle-card-v0955"><div class="battle-card-top"><div><button class="player-button" data-recruit="${battleEscape(r.id)}">${battleEscape(r.name)}</button> · ${battleEscape(r.pos)} · #${r.nationalRank} · ${'★'.repeat(r.stars)}</div><span class="pill">${battleEscape(window)}</span></div><div class="small muted">${battleEscape(r.highSchool)} · ${battleEscape(r.homeCity)}, ${battleEscape(r.homeState)} · ${battleEscape(momentumLabel(r))}${r.challenger?` · <span class="warn">challenged by ${battleEscape(r.challenger)}</span>`:''}</div><div class="battle-schools">${rows.map((x,i)=>`<span class="battle-school${x.t.id===t.id?' target':''}">${i+1}. ${battleEscape(x.t.name)} · ${Math.round(x.score)}</span>`).join('')}</div><div class="battle-card-actions">${focusButton(r,t)}<span class="small muted">${s.rank?`You: #${s.rank} · gap ${s.gap>=0?'+':''}${s.gap}`:'Outside top 3'}</span></div></div>`}).join('')||'<span class="muted">Target recruits to create active battles.</span>';attachRecruitLinks();bindRecruitFocus()}
 const renderRecruitBattlesBeforeV0955=renderRecruitBattles;
 renderRecruitBattles=function(){renderRecruitBattlesBeforeV0955();renderEnhancedBattleBoard()};
 const showRecruitProfileBeforeV0955Battles=showRecruitProfile;
 showRecruitProfile=function(id){showRecruitProfileBeforeV0955Battles(id);const r=universe.recruits.find(x=>String(x.id)===String(id)),t=selected(),body=$('#recruitDialogBody');if(r&&t&&body&&!body.querySelector('.recruit-race-card')){body.insertAdjacentHTML('afterbegin',raceCard(r,t));bindRecruitFocus()}};
 const renderRecruitingBeforeV0955Battles=renderRecruiting;
 renderRecruiting=function(){renderRecruitingBeforeV0955Battles();const t=selected(),summary=$('#classSummary');if(t&&summary&&!summary.querySelector('.recruit-focus-strip')){const used=recruitingBattleSystem.focusCount(universe.recruits,t,universe);summary.insertAdjacentHTML('beforeend',`<div class="recruit-focus-strip"><strong>Weekly Priority Push</strong><span>${used} / ${RECRUITING_FOCUS_LIMIT} assigned</span><small>Use these on your most important open battles or to help protect a challenged commitment.</small></div>`)}bindRecruitFocus()};
 if(typeof TAB_RENDERERS==='object')TAB_RENDERERS.recruiting=renderRecruiting;
 globalThis.DynastyLabRecruitingBattles={summary:r=>recruitingBattleSystem.raceSummary(battleRows(r,5),selected()?.id),toggle:r=>recruitingBattleSystem.toggleFocus(r,selected(),universe,RECRUITING_FOCUS_LIMIT)};
}
