from pathlib import Path

app = Path('app.js')
src = app.read_text()

if 'function validateImportedSaveText(value)' not in src:
    start = src.index('// Team name is the one user-editable string')
    end = src.index('function validateSave(d){', start)
    block = '''// Browser saves are generated by Dynasty Lab itself, so their hot load path only needs
// to re-check the one user-editable string that is widely rendered through innerHTML.
// Portable JSON imports are a different trust boundary: validateImportedSaveText() below
// walks those once before installation so an edited file cannot inject markup through
// player names, logs, IDs, recap text, or any other save-backed render surface.
function validateSaveText(u){
  for(const t of u.teams||[])
    if(typeof t?.name==='string'&&/[<>\"]/.test(t.name))
      throw new Error('Invalid dynasty save. A team name contains unsafe markup.');
}
function validateImportedSaveText(value){
  const pending=[value],seen=new WeakSet();
  while(pending.length){
    const current=pending.pop();
    if(typeof current==='string'){
      // Reject tag syntax everywhere. Ordinary quotation marks in generated prose are fine,
      // but a quote immediately followed by an attribute assignment can break out of a
      // quoted data/value attribute. Also reject active javascript: URL payloads.
      if(/[<>]/.test(current)||/[\"']\s*[A-Za-z_:][-A-Za-z0-9_:.]*\s*=/.test(current)||/\bjavascript\s*:/i.test(current))
        throw new Error('Invalid dynasty save. Imported text contains unsafe markup.');
      continue;
    }
    if(!current||typeof current!=='object'||seen.has(current))continue;
    seen.add(current);
    for(const item of Object.values(current))pending.push(item);
  }
}
'''
    src = src[:start] + block + src[end:]

import_anchor = "  installSave(d);setStatus('Imported save file successfully.');"
if 'validateImportedSaveText(d?.universe||d);' not in src:
    if import_anchor not in src:
        raise SystemExit('importSave install anchor not found')
    src = src.replace(import_anchor, "  validateImportedSaveText(d?.universe||d);\n" + import_anchor, 1)
app.write_text(src)

test = Path('tests/persistence.js')
t = test.read_text()
if 'const unsafeLog=' not in t:
    anchor = "  const before=e.universe;\n  await e.importSave('{bad json');"
    if anchor not in t:
        raise SystemExit('persistence test anchor not found')
    replacement = '''  // Portable imports are untrusted even when their shape matches a real export. Quotes in
  // ordinary generated prose remain valid, but markup and attribute-breakout payloads must
  // be rejected before installSave() can render any save-backed string.
  const quoted=JSON.parse(JSON.stringify(exported));quoted.universe.movementLog=['Coach "Ace" Miller was hired.'];
  await e.importSave(JSON.stringify(quoted));assert.match(e.$el('#saveStatus').textContent,/Imported/);
  const before=e.universe;
  const unsafeLog=JSON.parse(JSON.stringify(exported));unsafeLog.universe.movementLog=['<img src=x onerror=alert(1)>'];
  await e.importSave(JSON.stringify(unsafeLog));assert.equal(e.universe,before);
  assert.match(e.$el('#saveStatus').textContent,/unsafe markup/);
  const unsafeId=JSON.parse(JSON.stringify(exported));unsafeId.universe.teams[0].roster[0].id='p1" onmouseover=alert(1) data-x="';
  await e.importSave(JSON.stringify(unsafeId));assert.equal(e.universe,before);
  assert.match(e.$el('#saveStatus').textContent,/unsafe markup/);
  await e.importSave('{bad json');'''
    t = t.replace(anchor, replacement, 1)
test.write_text(t)
